/*************************************************************************
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 ************************************************************************/

#ifndef MSCCL_KERNEL_H_
#define MSCCL_KERNEL_H_

#define MSCCL_KERNEL_ENTRY_NAME(devredop, type, proto) mscclKernel_##devredop##_##type##_##proto

#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE_PROTO(devredop, type, proto) \
__global__ void MSCCL_KERNEL_ENTRY_NAME(devredop, type, proto)(struct ncclDevComm* comm, struct mscclAlgo* algo, struct mscclWork work);

#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, type) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE_PROTO(devredop, type, LL) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE_PROTO(devredop, type, LL128) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE_PROTO(devredop, type, Simple)

#if defined(__CUDA_BF16_TYPES_EXIST__) && defined(__CUDA_FP8_TYPES_EXIST__)
#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(devredop) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, half) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, float) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, double) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, __nv_bfloat16) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, __nv_fp8_e4m3) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, __nv_fp8_e5m2)
#elif defined(__CUDA_BF16_TYPES_EXIST__)
#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(devredop) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, half) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, float) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, double) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, __nv_bfloat16)
#else
#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(devredop) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, half) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, float) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, double)
#endif

#define MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_NOFLOAT(devredop) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint8_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint32_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, int64_t) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_TYPE(devredop, uint64_t)

#define MSCCL_DECL_KERNEL_ENTRY_FUNC() \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(Sum) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(Prod) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(MinMax) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP(PreMulSum) \
  MSCCL_DECL_KERNEL_ENTRY_FUNC_DEVREDOP_NOFLOAT(SumPostDiv)

MSCCL_DECL_KERNEL_ENTRY_FUNC()


#define PCCL_KERNEL_ENTRY_NAME(type) pcclKernel_Simple_Sum_##type

#define PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(type) \
__global__ void PCCL_KERNEL_ENTRY_NAME(type)(struct ncclDevComm* comm, struct mscclAlgo* algo, struct mscclWork work);

#if defined(__CUDA_BF16_TYPES_EXIST__) && defined(__CUDA_FP8_TYPES_EXIST__)
#define PCCL_DECL_KERNEL_ENTRY_FUNC() \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(half) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(float) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(double) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(__nv_bfloat16) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(__nv_fp8_e4m3) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(__nv_fp8_e5m2)
#elif defined(__CUDA_BF16_TYPES_EXIST__)
#define PCCL_DECL_KERNEL_ENTRY_FUNC() \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(half) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(float) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(double) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(__nv_bfloat16)
#else
#define PCCL_DECL_KERNEL_ENTRY_FUNC() \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint8_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint32_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(int64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(uint64_t) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(half) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(float) \
  PCCL_DECL_KERNEL_ENTRY_FUNC_TYPE(double)
#endif

PCCL_DECL_KERNEL_ENTRY_FUNC()


#endif
